apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bc-go-hello
  labels:
    app: bc-go-hello
spec:
  source:
    type: Git
    git:
      uri: https://github.com/cdoan1/bc-go-hello.git
      ref: main
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.21
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: bc-go-hello:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        name: golang:1.21
        namespace: openshift